################################################
# WhatIsThis configuration file                #
#                                              #
# Identify the block you are looking at by     #
# command, or right-click with an item.        #
# Author: steve4744                            #
################################################
# Check for new version
check_for_update: true
# Allow right-click with item
use_right_click:
  enabled: true
  item: STICK
# Translatable text
text:
  drops: Drops
# To enable the loading of specific languages only, add them to a list as follows:
#LoadLanguage: [en_us, es_es, cy_gb]
# Or
#LoadLanguage:
#- en_us
#- es_es
#- cy_gb
# If you want to load all the languages, add "all" to the list:
LoadLanguage:
- all
# Enable the preferred method(s) to display the block info
Display:
  scoreboard:
    enabled: true
  actionbar:
    enabled: false
    textcolor: WHITE
  bossbar: 
    enabled: false
    textcolor: WHITE
    barcolor: GREEN