#################################################
# WhatIsThis configuration file                 #
#                                               #
# Identify blocks simply by looking at them,    #
# by command or by right-clicking with an item. #
# Set the item to AIR to click with empty hand. #
# Setting "auto_display: true" will display     #
# block info without a command or clicking.     #
# Author: steve4744                             #
#################################################
# Check for new version
check_for_update: true
# Allow right-click with item
use_right_click:
  enabled: true
  item: STICK
# Translatable text
text:
  drops: Drops
# To enable the loading of specific languages only, add them to a list as follows:
#LoadLanguage: [en_us, es_es, cy_gb]
# Or
#LoadLanguage:
#- en_us
#- es_es
#- cy_gb
# If you want to load all the languages, add "all" to the list:
LoadLanguage:
- all
# Enable if you want to use the placeholders
PlaceholderAPI:
  enabled: false
# Enable the preferred method(s) to display the block info
Display:
  auto_display: false
  display_time: 60
  prefix_custom_blocks:
    enabled: true
    prefix: '&7[&f{PREFIX}&7] '
  scoreboard:
    enabled: true
  actionbar:
    enabled: false
    textcolor: WHITE
  bossbar: 
    enabled: false
    textcolor: WHITE
    barcolor: GREEN
  chat:
    enabled: false
    name_color: GREEN
    drop_color: RED
    show_drops: true
  ia_hud:
    enabled: true
    offset: 0
IgnoreBlocks:
- AIR
- CAVE_AIR
- WATER
- GRASS_BLOCK
- NETHERRACK